# Default values for storageos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: storageos/node
  tag: 0.10.0
  pullPolicy: IfNotPresent

## does your cluster have rbac enabled? assume no by default
rbacEnabled: false

cluster:
  # to generate a join token see:
  # https://docs.storageos.com/docs/install/prerequisites/clusterdiscovery
  join: 

  # sharedDir should be set if running kubelet in a container.  This should
  # be the path shared into to kubelet container, typically:
  # "/var/lib/kubelet/plugins/kubernetes.io~storageos".  If not set, defaults
  # will be used.
  sharedDir:
storageclass:
  name: fast
  pool: default
  fsType: ext4
api:
  secretName: storageos-api
  secretNamespace: default
  # secrets are namespace specific, create 1+N for every namespace.
  address: storageos:5705
  # address is used to generate the ApiAddress value in the secret. This
  # updated later with the service ClusterIP which is not known yet.
  username: storageos
  password: storageos
service:
  name: storageos
  namespace: default
  type: ClusterIP
  externalPort: 5705
  internalPort: 5705
resources: {}
